on: push
jobs:
  producer:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo TEST > file.txt
          tar -czf file.tgz file.txt
      - uses: actions/upload-artifact@v2
        with:
          name: a-different-name.tgz
          path: file.tgz

  consumer--no-path:
    needs: producer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: a-different-name.tgz
      - run: |
          find .
          tar -xzf a-different-name.tgz
          find .

  consumer--with-path:
    needs: producer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: a-different-name.tgz
          path: a-different-name.tgz
      - run: |
          find .
          tar -xzf a-different-name.tgz
          find .
